# Site settings
title: Sciences And Technology
email: http://uin-suska.ac.id/
url: http://uin-suska.ac.id/
description: "Fakultas Sains dan Teknologi didirikan pada akhir tahun 2001 sebagai persiapan perubahan status dari Institut Agama Islam Negeri Sultan Syarif Qasim (IAIN SUSQA) Pekanbaru menjadi Universitas Islam Negeri Sultan Syarif Kasim Riau (UIN Suska) Riau."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: abdurrahimradhin

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
- title: Universitas Islam Negeri Sultan Syarif Kasim 
    url: http://uin-suska.ac.id/
  - title: SISTEM INFORMASI
    url: http://sif.uin-suska.ac.id/
  - title: TEKNIK INFORMATIKA
    url: http://tif.uin-suska.ac.id
  - title: TEKNIK INDUSTRI
    url:  http://ie.uin-suska.ac.id
  - title: MATEMATIKA
    url: http://math.uin-suska.ac.id
  - title: TEKNIK ELEKTRO
    url: http://ee.uin-suska.ac.id
# Build settings
markdown: kramdown
permalink: pretty
